// Godot 4 exporter: a .tscn scene with Skeleton2D + Bone2D + a skinned
// Polygon2D.
//
// Godot's 2D skinning maps onto our rig almost directly:
//   Polygon2D.polygon   — the contour, in pixels
//   Polygon2D.uv        — same coordinates, since the texture is the sprite
//   Polygon2D.polygons  — triangle index lists
//   Polygon2D.bones     — flat [NodePath, weights] pairs, one weight per vertex
//   Bone2D.rest         — Transform2D of the bone's rest pose
//
// Godot has no built-in 2D spring constraint, so physics is emitted as script
// metadata on each bone plus a small companion script the user can attach. That
// keeps the parameters with the scene instead of silently dropping them.

import { restTransforms, boneSegment, type Bone } from './skeleton';
import type { Mesh } from './triangulate';
import { getWeight, type Weights } from './weights';

export interface GodotExportInput {
  spriteName: string;
  region: { x: number; y: number; width: number; height: number };
  bones: Bone[];
  mesh: Mesh;
  weights: Weights;
  /** Resource path of the sprite texture inside the Godot project. */
  texturePath?: string;
}

function fmt(value: number, digits = 4): string {
  const rounded = Number(value.toFixed(digits));
  return Object.is(rounded, -0) ? '0' : String(rounded);
}

/** Godot node names cannot contain . : @ / " or %. */
function safeName(name: string): string {
  return name.replace(/[.:@/"%]/g, '_') || 'bone';
}

/**
 * Emits a Godot 4 `.tscn`. Bones become a flat list of Bone2D nodes under one
 * Skeleton2D, each with its rest transform baked in world space — Godot applies
 * a Bone2D's own transform relative to its parent node, and keeping the
 * hierarchy flat avoids re-deriving nested transforms here.
 */
export function buildGodotScene(input: GodotExportInput): string {
  const { spriteName, region, bones, mesh, weights } = input;
  const texturePath = input.texturePath ?? `res://${spriteName}.png`;

  const transforms = restTransforms(bones);
  const vertexCount = mesh.vertices.length / 2;

  // ── polygon, uv, triangles ────────────────────────────────────────────────
  const polygon: string[] = [];
  const uv: string[] = [];
  for (let v = 0; v < vertexCount; v++) {
    const x = mesh.vertices[v * 2];
    const y = mesh.vertices[v * 2 + 1];
    polygon.push(`${fmt(x)}, ${fmt(y)}`);
    // The texture is the cropped sprite, so UVs are the same pixel coords.
    uv.push(`${fmt(x)}, ${fmt(y)}`);
  }

  const tris: string[] = [];
  for (let t = 0; t < mesh.triangles.length; t += 3) {
    tris.push(
      `PackedInt32Array(${mesh.triangles[t]}, ${mesh.triangles[t + 1]}, ${mesh.triangles[t + 2]})`
    );
  }

  // ── bone weight arrays: Godot wants one weight per polygon vertex ─────────
  const boneEntries: string[] = [];
  for (const bone of bones) {
    const perVertex: string[] = [];
    let any = false;
    for (let v = 0; v < vertexCount; v++) {
      const w = getWeight(weights, v, bone.id);
      if (w > 0) any = true;
      perVertex.push(fmt(w, 5));
    }
    // Skip bones that influence nothing; Godot would just carry dead arrays.
    if (!any) continue;
    boneEntries.push(
      `NodePath("Skeleton2D/${safeName(bone.name)}"), PackedFloat32Array(${perVertex.join(', ')})`
    );
  }

  // ── bone nodes ────────────────────────────────────────────────────────────
  const boneNodes: string[] = [];
  for (const bone of bones) {
    const m = transforms.get(bone.id);
    if (!m) continue;
    const { end } = boneSegment(bone, transforms);
    // Transform2D takes the basis columns then the origin.
    const rest = `Transform2D(${fmt(m[0])}, ${fmt(m[1])}, ${fmt(m[2])}, ${fmt(m[3])}, ${fmt(m[4])}, ${fmt(m[5])})`;
    const meta = bone.physics?.enabled
      ? `
metadata/physics_stiffness = ${fmt(bone.physics.stiffness)}
metadata/physics_damping = ${fmt(bone.physics.damping)}
metadata/physics_gravity = ${fmt(bone.physics.gravity)}
metadata/physics_inertia = ${fmt(bone.physics.inertia)}`
      : '';
    boneNodes.push(
      `[node name="${safeName(bone.name)}" type="Bone2D" parent="Skeleton2D"]
position = Vector2(${fmt(m[4])}, ${fmt(m[5])})
rest = ${rest}
auto_calculate_length_and_angle = false
length = ${fmt(bone.length)}
bone_angle = ${fmt((Math.atan2(end.y - m[5], end.x - m[4]) * 180) / Math.PI)}${meta}`
    );
  }

  const loadSteps = 2;
  return `; Godot 4 scene generated by SpriteCutter.
; Attach spring_bones.gd to the Skeleton2D to drive the physics metadata.

[gd_scene load_steps=${loadSteps} format=3]

[ext_resource type="Texture2D" path="${texturePath}" id="1_tex"]

[node name="${safeName(spriteName)}" type="Node2D"]

[node name="Skeleton2D" type="Skeleton2D" parent="."]

${boneNodes.join('\n\n')}

[node name="Polygon2D" type="Polygon2D" parent="."]
texture = ExtResource("1_tex")
polygon = PackedVector2Array(${polygon.join(', ')})
uv = PackedVector2Array(${uv.join(', ')})
polygons = [${tris.join(', ')}]
skeleton = NodePath("../Skeleton2D")
bones = [${boneEntries.join(', ')}]
`;
}

/**
 * Companion GDScript implementing the same damped spring our editor previews,
 * reading the per-bone metadata the scene carries. Shipped alongside the scene
 * so Godot users get the secondary motion rather than just the parameters.
 */
export function godotSpringScript(): string {
  return `# spring_bones.gd — secondary motion for Bone2D chains.
# Generated by SpriteCutter to match its editor preview.
#
# Attach to a Skeleton2D. Any Bone2D child carrying metadata/physics_* is
# simulated as a damped angular spring that lags behind its parent, the same
# model Spine's physics constraints use.
extends Skeleton2D

const FIXED_STEP := 1.0 / 60.0
const MAX_STEPS := 4

class SpringBone:
	var bone: Bone2D
	var rest_rotation: float
	var stiffness: float
	var damping: float
	var gravity: float
	var inertia: float
	var velocity: float = 0.0
	var last_parent_pos: Vector2
	var has_last: bool = false

var _springs: Array[SpringBone] = []
var _accumulator := 0.0

func _ready() -> void:
	for child in get_children():
		if child is Bone2D and child.has_meta("physics_stiffness"):
			var s := SpringBone.new()
			s.bone = child
			s.rest_rotation = child.rotation
			s.stiffness = child.get_meta("physics_stiffness", 0.35)
			s.damping = child.get_meta("physics_damping", 0.6)
			s.gravity = child.get_meta("physics_gravity", 0.15)
			s.inertia = child.get_meta("physics_inertia", 0.85)
			_springs.append(s)

func _process(delta: float) -> void:
	if _springs.is_empty():
		return
	_accumulator += minf(delta, 0.25)
	var steps := 0
	while _accumulator >= FIXED_STEP and steps < MAX_STEPS:
		_step()
		_accumulator -= FIXED_STEP
		steps += 1
	if steps >= MAX_STEPS:
		_accumulator = 0.0

func _step() -> void:
	for s in _springs:
		var offset := s.bone.rotation - s.rest_rotation

		# Drag: how far this bone's origin moved since the last step. Motion
		# perpendicular to the shaft is what swings it.
		var drag := 0.0
		var pos := s.bone.global_position
		if s.has_last:
			var move := pos - s.last_parent_pos
			var angle := s.bone.global_rotation
			var perpendicular := -move.x * sin(angle) + move.y * cos(angle)
			drag = -perpendicular * s.inertia * 0.05
		s.last_parent_pos = pos
		s.has_last = true

		# Gravity pulls the tip toward world +Y, strongest when horizontal.
		var gravity_torque := cos(s.bone.global_rotation) * s.gravity * 0.6
		var spring := -offset * s.stiffness

		var next := (s.velocity + spring + gravity_torque + drag) * (1.0 - s.damping)
		if not is_finite(next):
			next = 0.0
		next = clampf(next, -1.0, 1.0)
		s.velocity = next
		s.bone.rotation = s.rest_rotation + clampf(offset + next, -PI, PI)
`;
}
