// Unity exporter.
//
// Unity's 2D Animation rig (SpriteBone + bone weights) lives *inside* the
// sprite asset, written through the editor-only SpriteDataAccessExtensions API.
// There is no documented text format we could emit directly, so instead of
// guessing at a .asset layout that Unity may reject, this emits:
//
//   1. the neutral rig JSON (from exportRig.ts), and
//   2. a C# editor script that reads it and applies the rig to a Sprite via
//      the official API.
//
// That keeps the round trip honest: the data is ours, the writing is Unity's.

/** C# editor script that applies a SpriteCutter rig JSON to a sprite asset. */
export function unityImporterScript(): string {
  return `// SpriteCutterRigImporter.cs
// Generated by SpriteCutter. Put this under an "Editor" folder.
//
// Applies a SpriteCutter rig JSON (bones + mesh + skinning weights) to a
// Sprite asset using Unity's 2D Animation data-access API, so the sprite can be
// driven by a SpriteSkin component at runtime.
//
// Requires: com.unity.2d.animation (Window > Package Manager).
// Usage: select the sprite's texture in the Project window, then
//        Window > SpriteCutter > Apply Rig JSON.
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.U2D.Sprites;
using UnityEngine;

namespace SpriteCutter
{
    [Serializable] public class RigSprite { public string name; public float x, y, width, height; }
    [Serializable] public class RigBone
    {
        public string name;
        public string parent;
        public float x, y, rotation, length;
        public RigPhysics physics;
    }
    [Serializable] public class RigPhysics
    {
        public bool enabled;
        public float stiffness, damping, gravity, inertia;
    }
    [Serializable] public class RigMesh
    {
        public float[] vertices;
        public int[] triangles;
        public float[] uvs;
        public int contourCount;
    }
    [Serializable] public class RigDocument
    {
        public string format;
        public int version;
        public RigSprite sprite;
        public RigBone[] bones;
        public RigMesh mesh;
        // Per-vertex: [count, boneIndex, weight, boneIndex, weight, ...]
        public List<List<float>> skinning;
    }

    public static class SpriteCutterRigImporter
    {
        [MenuItem("Window/SpriteCutter/Apply Rig JSON")]
        public static void ApplyRig()
        {
            var texture = Selection.activeObject as Texture2D;
            if (texture == null)
            {
                EditorUtility.DisplayDialog("SpriteCutter",
                    "Select the sprite's texture in the Project window first.", "OK");
                return;
            }

            var jsonPath = EditorUtility.OpenFilePanel("SpriteCutter rig JSON", "", "json");
            if (string.IsNullOrEmpty(jsonPath)) return;

            var doc = JsonUtility.FromJson<RigDocument>(File.ReadAllText(jsonPath));
            if (doc == null || doc.bones == null || doc.mesh == null)
            {
                Debug.LogError("SpriteCutter: could not parse the rig JSON.");
                return;
            }

            var assetPath = AssetDatabase.GetAssetPath(texture);
            var factories = new SpriteDataProviderFactories();
            factories.Init();
            var provider = factories.GetSpriteEditorDataProviderFromObject(
                AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(assetPath));
            if (provider == null)
            {
                Debug.LogError("SpriteCutter: no sprite data provider for " + assetPath);
                return;
            }
            provider.InitSpriteEditorDataProvider();

            var boneProvider = provider.GetDataProvider<ISpriteBoneDataProvider>();
            var meshProvider = provider.GetDataProvider<ISpriteMeshDataProvider>();
            if (boneProvider == null || meshProvider == null)
            {
                Debug.LogError("SpriteCutter: install com.unity.2d.animation first.");
                return;
            }

            var rects = provider.GetSpriteRects();
            if (rects.Length == 0)
            {
                Debug.LogError("SpriteCutter: the texture has no sprites.");
                return;
            }
            var guid = rects[0].spriteID;

            // ── bones ────────────────────────────────────────────────────────
            // Unity is y-up with positions relative to the sprite rect, so the
            // vertical axis is flipped from SpriteCutter's y-down space.
            var height = doc.sprite.height;
            var nameToIndex = new Dictionary<string, int>();
            for (int i = 0; i < doc.bones.Length; i++) nameToIndex[doc.bones[i].name] = i;

            var bones = new List<SpriteBone>();
            for (int i = 0; i < doc.bones.Length; i++)
            {
                var b = doc.bones[i];
                int parentIndex = -1;
                if (!string.IsNullOrEmpty(b.parent))
                    nameToIndex.TryGetValue(b.parent, out parentIndex);

                bones.Add(new SpriteBone
                {
                    name = b.name,
                    parentId = parentIndex,
                    // A root bone's position is absolute in the sprite; a child's
                    // is already relative to its parent, so only roots flip.
                    position = parentIndex < 0
                        ? new Vector3(b.x, height - b.y, 0f)
                        : new Vector3(b.x, -b.y, 0f),
                    rotation = Quaternion.Euler(0f, 0f, -b.rotation),
                    length = b.length,
                });
            }
            boneProvider.SetBones(guid, bones);

            // ── mesh vertices + weights ──────────────────────────────────────
            int vertexCount = doc.mesh.vertices.Length / 2;
            var vertices = new Vector2[vertexCount];
            var weights = new BoneWeight[vertexCount];

            for (int v = 0; v < vertexCount; v++)
            {
                vertices[v] = new Vector2(
                    doc.mesh.vertices[v * 2],
                    height - doc.mesh.vertices[v * 2 + 1]);

                var w = new BoneWeight();
                if (doc.skinning != null && v < doc.skinning.Count)
                {
                    var row = doc.skinning[v];
                    int count = row.Count > 0 ? (int)row[0] : 0;
                    for (int k = 0; k < count && k < 4; k++)
                    {
                        int bi = (int)row[1 + k * 2];
                        float bw = row[2 + k * 2];
                        switch (k)
                        {
                            case 0: w.boneIndex0 = bi; w.weight0 = bw; break;
                            case 1: w.boneIndex1 = bi; w.weight1 = bw; break;
                            case 2: w.boneIndex2 = bi; w.weight2 = bw; break;
                            case 3: w.boneIndex3 = bi; w.weight3 = bw; break;
                        }
                    }
                }
                weights[v] = w;
            }

            meshProvider.SetVertices(guid, vertices);
            meshProvider.SetWeights(guid, weights);
            meshProvider.SetIndices(guid, doc.mesh.triangles);

            provider.Apply();
            var importer = AssetImporter.GetAtPath(assetPath);
            EditorUtility.SetDirty(importer);
            importer.SaveAndReimport();

            Debug.Log($"SpriteCutter: applied {bones.Count} bones and " +
                      $"{vertexCount} weighted vertices to {texture.name}. " +
                      "Add a SpriteSkin component to the sprite in a scene.");
        }
    }
}
`;
}

/**
 * Unity has no 2D spring constraint either, so the spring parameters ride along
 * as a MonoBehaviour matching the editor preview.
 */
export function unitySpringScript(): string {
  return `// SpriteCutterSpringBone.cs
// Generated by SpriteCutter. Damped angular spring for secondary motion,
// matching the editor preview. Attach to a bone Transform under a SpriteSkin.
using UnityEngine;

namespace SpriteCutter
{
    public class SpriteCutterSpringBone : MonoBehaviour
    {
        [Tooltip("Springiness back toward the rest angle.")]
        [Range(0.02f, 1f)] public float stiffness = 0.35f;
        [Tooltip("Velocity decay per step; higher settles faster.")]
        [Range(0.05f, 0.95f)] public float damping = 0.6f;
        [Tooltip("Downward pull, strongest when the bone is horizontal.")]
        [Range(0f, 1f)] public float gravity = 0.15f;
        [Tooltip("How much parent motion drags this bone along.")]
        [Range(0f, 2f)] public float inertia = 0.85f;

        const float FixedStep = 1f / 60f;
        const int MaxSteps = 4;

        float _restRotation;
        float _velocity;
        float _accumulator;
        Vector3 _lastPosition;
        bool _hasLast;

        void Start()
        {
            _restRotation = transform.localEulerAngles.z;
            _lastPosition = transform.position;
        }

        void Update()
        {
            _accumulator += Mathf.Min(Time.deltaTime, 0.25f);
            int steps = 0;
            while (_accumulator >= FixedStep && steps < MaxSteps)
            {
                Step();
                _accumulator -= FixedStep;
                steps++;
            }
            if (steps >= MaxSteps) _accumulator = 0f;
        }

        void Step()
        {
            float current = transform.localEulerAngles.z;
            float offset = Mathf.DeltaAngle(_restRotation, current) * Mathf.Deg2Rad;

            // Drag from this bone's own world motion, perpendicular to the shaft.
            float drag = 0f;
            Vector3 position = transform.position;
            if (_hasLast)
            {
                Vector3 move = position - _lastPosition;
                float angle = transform.eulerAngles.z * Mathf.Deg2Rad;
                float perpendicular = -move.x * Mathf.Sin(angle) + move.y * Mathf.Cos(angle);
                // Unity is y-up, so the sign flips relative to the y-down editor.
                drag = perpendicular * inertia * 0.05f;
            }
            _lastPosition = position;
            _hasLast = true;

            float gravityTorque = -Mathf.Cos(transform.eulerAngles.z * Mathf.Deg2Rad) * gravity * 0.6f;
            float spring = -offset * stiffness;

            float next = (_velocity + spring + gravityTorque + drag) * (1f - damping);
            if (float.IsNaN(next) || float.IsInfinity(next)) next = 0f;
            _velocity = Mathf.Clamp(next, -1f, 1f);

            float nextOffset = Mathf.Clamp(offset + _velocity, -Mathf.PI, Mathf.PI);
            var euler = transform.localEulerAngles;
            euler.z = _restRotation + nextOffset * Mathf.Rad2Deg;
            transform.localEulerAngles = euler;
        }
    }
}
`;
}
